export { default as HomeView } from './HomeView.vue'
export { default as ProjectView } from './ProjectView.vue'
export { default as ContributorsView } from './ContributorsView.vue'
export { default as DiscoveryView } from './DiscoveryView.vue'
export { default as DiscoveryWorkshopView } from './DiscoveryWorkshopView.vue'
export { default as PublicationsView } from './PublicationsView.vue'
export { default as SupportView } from './SupportView.vue'